[{
	"resource": "/d:/Рабочий стол/WCD/V2/gm-assistant/src/app/api/ai/route.ts",
	"owner": "typescript",
	"code": "2349",
	"severity": 8,
	"message": "Это выражение не является вызываемым.\n  Тип \"{ error: any; }\" не содержит сигнатуры вызова.",
	"source": "ts",
	"startLineNumber": 51,
	"startColumn": 32,
	"endLineNumber": 51,
	"endColumn": 42,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/d:/Рабочий стол/WCD/V2/gm-assistant/src/app/api/ai/route.ts",
	"owner": "typescript",
	"code": "1127",
	"severity": 8,
	"message": "Недопустимый символ.",
	"source": "ts",
	"startLineNumber": 51,
	"startColumn": 41,
	"endLineNumber": 51,
	"endColumn": 41,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/d:/Рабочий стол/WCD/V2/gm-assistant/src/app/api/ai/route.ts",
	"owner": "typescript",
	"code": "1136",
	"severity": 8,
	"message": "Ожидалось назначение свойства.",
	"source": "ts",
	"startLineNumber": 51,
	"startColumn": 42,
	"endLineNumber": 74,
	"endColumn": 2,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/d:/Рабочий стол/WCD/V2/gm-assistant/src/app/api/ai/route.ts",
	"owner": "typescript",
	"code": "1160",
	"severity": 8,
	"message": "Незавершенный литерал шаблона.",
	"source": "ts",
	"startLineNumber": 74,
	"startColumn": 2,
	"endLineNumber": 74,
	"endColumn": 2,
	"modelVersionId": 3,
	"origin": "extHost1"
}]